site_name: mdbackup documentation
repo_url: https://github.com/MajorcaDevs/mdbackup
repo_name: MajorcaDevs/mdbackup
edit_uri: blob/dev
site_description: mdbackup documentation
copyright: MajorcaDevs 2022
docs_dir: docs
site_dir: build/docs
strict: true
theme:
  name: material
  language: 'en'
  icon:
    logo: material/archive-arrow-up
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
markdown_extensions:
  # admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # content tabs
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike
    default: stable
nav:
  - Home: 'README.md'
  - Quick start: 'quick-start.md'
  - Configuration: 'configuration.md'
  - Actions:
    - Actions overview: 'actions/index.md'
    - Builtin actions:
      - Archive: 'actions/archive.md'
      - Command: 'actions/command.md'
      - Compress: 'actions/compress.md'
      - Database: 'actions/database.md'
      - Directory: 'actions/directory.md'
      - Encrypt: 'actions/encrypt.md'
      - File: 'actions/file.md'
      - Network: 'actions/network.md'
  - Tasks: 'tasks.md'
  - Storage providers:
    - Overview: 'storage/index.md'
    - Google Drive: 'storage/gdrive.md'
    - S3: 'storage/s3.md'
    - B2: 'storage/b2.md'
    - FTP(S): 'storage/ftp.md'
    - SFTP: 'storage/sftp.md'
  - Secrets providers:
      - Overview: 'secrets/index.md'
      - File: 'secrets/file.md'
      - Vault: 'secrets/vault.md'
  - Hooks: 'hooks.md'
  - Arguments: 'arguments.md'
  - Run as a service: 'run-as-service.md'
  - Docker: 'docker.md'
