ARG ARCH='amd64'

FROM ${ARCH}/python:3.8-slim
LABEL owner="MajorcaDevs"

COPY ./docker/requirements.txt /mdbackup/requirements.txt
RUN apt update && \
    apt install rsync ssh tar xz-utils gcc make python3-dev libffi-dev libssl-dev gpg gzip -y && \
    pip install -r /mdbackup/requirements.txt && \
    apt autoremove gcc make python3-dev libffi-dev libssl-dev -y && \
    apt autoremove -y && \
    apt clean -y && \
    rm -rf /var/cache/apt

COPY ./mdbackup/ /mdbackup/mdbackup
COPY ./MANIFEST.in /mdbackup
COPY ./README.md /mdbackup
COPY ./setup.py /mdbackup
WORKDIR /mdbackup
VOLUME /backups

RUN pip install .
