# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM python:3.12-alpine AS deps

WORKDIR /src
RUN pip install pipenv
COPY ./Pipfile ./Pipfile.lock .
RUN pipenv requirements > requirements.txt


FROM python:3.12-slim
LABEL owner="MajorcaDevs"

COPY --from=deps /src/requirements.txt /mdbackup/requirements.txt
RUN apt update && \
    apt install rsync ssh tar xz-utils gcc make python3-dev libffi-dev libssl-dev gpg gzip -y && \
    pip install -r /mdbackup/requirements.txt && \
    apt autoremove gcc make python3-dev libffi-dev libssl-dev -y && \
    apt autoremove -y && \
    apt clean -y && \
    rm -rf /var/cache/apt

COPY ./mdbackup/ /mdbackup/mdbackup
COPY ./MANIFEST.in /mdbackup
COPY ./README.md /mdbackup
COPY ./setup.py /mdbackup
WORKDIR /mdbackup
VOLUME /backups

RUN pip install .
