ARG ARCH='amd64'

FROM ${ARCH}/python:3.7-alpine

LABEL owner="MajorcaDevs"
COPY ./mdbackup/ /mdbackup/mdbackup
COPY ./MANIFEST.in /mdbackup
COPY ./README.md /mdbackup
COPY ./setup.py /mdbackup
WORKDIR mdbackup

RUN mkdir /backups && \
apk add bash rsync openssh tar xz gnupg gzip musl-dev libffi-dev openssl-dev --no-cache && \
apk add --virtual .bdeps gcc make --no-cache && pip install . && \ 
pip install python-magic boto3 b2sdk PyDrive requests==2.19.1 pyyaml paramiko urllib3==1.21.1 && \
apk del .bdeps && rm -rf /var/cache/apk/

