name: PR build

on:
  push:
    branches: [ 'dev' ]
  pull_request:
    branches: [ 'dev' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --dev
      - name: Code Style
        run: |
          python -m pipenv run flake8 mdbackup
          python -m pipenv run flake8 tests
      - name: Test
        run: |
          python -m pipenv run coverage run --source=mdbackup --branch -m xmlrunner discover -s tests -p '*tests*.py' -o tests/.report
          python -m pipenv run coverage html -d tests/.coverage-report/
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/.report/**/*.xml
          retention-days: 30
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: tests/.coverage-report/**/*.html
          retention-days: 30

  docker:
    strategy:
      matrix:
        flavour:
          - alpine
          - slim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile-${{ matrix.flavour }}
          push: false
          platforms: linux/amd64
